spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:~/data/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:~/data/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver